const actionTypes = {
  SET_DATA: 'SET_DATA',
  SET_LOADING: 'SET_LOADING',
  SET_ACTIVE: 'SET_ACTIVE',
  SET_SEARCH_WORD: 'SET_SEARCH_WORD',
  SET_SELECT_VALUE: 'SET_SELECT_VALUE',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};

export default actionTypes;
